### ISSUE TITLE
Regarding Eq (5) in the Paper

### ISSUE THREAD

**Issue by QiyaoWei** [ZhaozhiQIAN/D-CODE-ICLR-2022#2]
Dear Zhaozhi,

Hope this message finds you well. Thanks a lot for this brilliant paper! I am writing to ask about Eq (5) in the paper, because I was not able to find an implementation of that in the code. As I understand, [this line](https://github.com/ZhaozhiQIAN/D-CODE-ICLR-2022/blob/556c84ea1f0fda2399ef47842afe20b724085605/gp_utils.py#L117) is where Eq(5) should appear in some way---please kindly correct me if I misunderstood!

**Comment by ZhaozhiQIAN** [comment]
Hi Qiyao, 

Thanks for reaching out. Equation 5 is an optimization problem and it is implemented in the `SymbolicODE` class in `genetic.py`. We adopted the sklearn convention to design the interface. The line you pointed out relates to the benchmarks (SR-T and so on).

**Comment by QiyaoWei** [comment]
Ah I see. Thank you so much for the quick reply!
